export {
    AddProfileFromURL,
    CloseWindow,
    CloseAllConnections,
    CloseConnection,
    DeleteProfile,
    FetchConnections,
    FetchProviders,
    FetchProxyGroups,
    FetchRules,
    GetLogs,
    GetSnapshot,
    ImportProfile,
    MinimizeWindow,
    OpenDataDirectory,
    OpenURL,
    ReadBackgroundImageDataURL,
    ReadProfileContent,
    RestartCore,
    SaveProfileContent,
    SaveSettings,
    SelectBackgroundImage,
    SelectProxy,
    SetActiveProfile,
    StartCore,
    StopCore,
    TestProxyGroup,
    UpdateProfile,
    UpdateProvider,
} from '../wailsjs/go/pulse/App';
export {pulse as Models} from '../wailsjs/go/models';
export {WindowToggleMaximise} from '../wailsjs/runtime/runtime';
