export {
    AddProfileFromURL,
    CloseWindow,
    CloseAllConnections,
    CloseConnection,
    DeleteProfile,
    FetchConnections,
    FetchProviders,
    FetchProxyGroups,
    FetchRules,
    GetLogs,
    GetSnapshot,
    ImportProfile,
    ImportProfileFromFile,
    MinimizeWindow,
    OpenDataDirectory,
    OpenURL,
    ReadBackgroundImageDataURL,
    ReadProfileContent,
    ReadProfileCustomRules,
    ReadProfileRulePolicies,
    RestartCore,
    SaveProfileContent,
    SaveProfileCustomRules,
    SaveSettings,
    SelectBackgroundImage,
    SelectProxy,
    SetActiveProfile,
    StartCore,
    StopCore,
    TestProxyGroup,
    TestProxyNode,
    UpdateProfile,
    UpdateProvider,
} from '../wailsjs/go/pulse/App';
export {pulse as Models} from '../wailsjs/go/models';
export {OnFileDrop, OnFileDropOff, WindowToggleMaximise} from '../wailsjs/runtime/runtime';
