// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pulse} from '../models';

export function AddProfileFromURL(arg1:string,arg2:string):Promise<pulse.Profile>;

export function CloseAllConnections():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function EnsureGeodata():Promise<void>;

export function FetchConnections():Promise<pulse.ConnectionSnapshot>;

export function FetchProviders():Promise<Array<pulse.ProviderRow>>;

export function FetchProxyGroups():Promise<Array<pulse.ProxyGroup>>;

export function FetchRules():Promise<Array<pulse.RuleRow>>;

export function GetLogs():Promise<Array<pulse.LogLine>>;

export function GetSnapshot():Promise<pulse.RuntimeState>;

export function ImportProfile(arg1:string,arg2:string):Promise<pulse.Profile>;

export function MinimizeWindow():Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadBackgroundImageDataURL(arg1:string):Promise<string>;

export function ReadProfileContent(arg1:string):Promise<string>;

export function ReadProfileCustomRules(arg1:string):Promise<Array<pulse.CustomRule>>;

export function RestartCore():Promise<void>;

export function SaveProfileContent(arg1:string,arg2:string):Promise<void>;

export function SaveProfileCustomRules(arg1:string,arg2:Array<pulse.CustomRule>):Promise<void>;

export function SaveSettings(arg1:pulse.Settings):Promise<void>;

export function SelectBackgroundImage():Promise<string>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;

export function TestProxyGroup(arg1:string):Promise<void>;

export function TestProxyNode(arg1:string,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string):Promise<pulse.Profile>;

export function UpdateProvider(arg1:string):Promise<void>;
