// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH 脗 MODIWL
// This file is automatically generated. DO NOT EDIT


export function AddProxyNode(arg1, arg2) {
  return window['go']['pulse']['App']['AddProxyNode'](arg1, arg2);
}

export function AddRelayGroup(arg1, arg2) {
  return window['go']['pulse']['App']['AddRelayGroup'](arg1, arg2);
}

export function GetProfileProxyNames(arg1) {
  return window['go']['pulse']['App']['GetProfileProxyNames'](arg1);
}

export function RemoveProxyNode(arg1, arg2) {
  return window['go']['pulse']['App']['RemoveProxyNode'](arg1, arg2);
}

export function AddProfileFromURL(arg1, arg2) {
  return window['go']['pulse']['App']['AddProfileFromURL'](arg1, arg2);
}

export function ApplyUpdate() {
  return window['go']['pulse']['App']['ApplyUpdate']();
}

export function CheckForUpdates() {
  return window['go']['pulse']['App']['CheckForUpdates']();
}

export function CloseAllConnections() {
  return window['go']['pulse']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['pulse']['App']['CloseConnection'](arg1);
}

export function CloseWindow() {
  return window['go']['pulse']['App']['CloseWindow']();
}

export function DeleteProfile(arg1) {
  return window['go']['pulse']['App']['DeleteProfile'](arg1);
}

export function DeleteBackgroundImage(arg1) {
  return window['go']['pulse']['App']['DeleteBackgroundImage'](arg1);
}

export function ExitKeepServiceRunning() {
  return window['go']['pulse']['App']['ExitKeepServiceRunning']();
}

export function EnsureGeodata() {
  return window['go']['pulse']['App']['EnsureGeodata']();
}

export function FetchConnections() {
  return window['go']['pulse']['App']['FetchConnections']();
}

export function FetchProviders() {
  return window['go']['pulse']['App']['FetchProviders']();
}

export function FetchProxyGroups() {
  return window['go']['pulse']['App']['FetchProxyGroups']();
}

export function FetchRules() {
  return window['go']['pulse']['App']['FetchRules']();
}

export function GetLogs() {
  return window['go']['pulse']['App']['GetLogs']();
}

export function GetSnapshot() {
  return window['go']['pulse']['App']['GetSnapshot']();
}

export function ImportProfile(arg1, arg2) {
  return window['go']['pulse']['App']['ImportProfile'](arg1, arg2);
}

export function ImportProfileFromFile(arg1) {
  return window['go']['pulse']['App']['ImportProfileFromFile'](arg1);
}

export function IsAdministrator() {
  return window['go']['pulse']['App']['IsAdministrator']();
}

export function ListBackgroundImages() {
  return window['go']['pulse']['App']['ListBackgroundImages']();
}

export function ListNetworkInterfaces() {
  return window['go']['pulse']['App']['ListNetworkInterfaces']();
}

export function MinimizeWindow() {
  return window['go']['pulse']['App']['MinimizeWindow']();
}

export function OpenDataDirectory() {
  return window['go']['pulse']['App']['OpenDataDirectory']();
}

export function OpenURL(arg1) {
  return window['go']['pulse']['App']['OpenURL'](arg1);
}

export function ReadBackgroundImageDataURL(arg1) {
  return window['go']['pulse']['App']['ReadBackgroundImageDataURL'](arg1);
}

export function ReadProfileContent(arg1) {
  return window['go']['pulse']['App']['ReadProfileContent'](arg1);
}

export function ReadProfileCustomRules(arg1) {
  return window['go']['pulse']['App']['ReadProfileCustomRules'](arg1);
}

export function ReadProfileRulePolicies(arg1) {
  return window['go']['pulse']['App']['ReadProfileRulePolicies'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['pulse']['App']['RenameProfile'](arg1, arg2);
}

export function RelaunchAsAdministrator() {
  return window['go']['pulse']['App']['RelaunchAsAdministrator']();
}

export function RestartCore() {
  return window['go']['pulse']['App']['RestartCore']();
}

export function SaveProfileContent(arg1, arg2) {
  return window['go']['pulse']['App']['SaveProfileContent'](arg1, arg2);
}

export function SaveProfileCustomRules(arg1, arg2) {
  return window['go']['pulse']['App']['SaveProfileCustomRules'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['pulse']['App']['SaveSettings'](arg1);
}

export function SelectBackgroundImage() {
  return window['go']['pulse']['App']['SelectBackgroundImage']();
}

export function SelectProxy(arg1, arg2) {
  return window['go']['pulse']['App']['SelectProxy'](arg1, arg2);
}

export function SetActiveProfile(arg1) {
  return window['go']['pulse']['App']['SetActiveProfile'](arg1);
}

export function ShowWindow() {
  return window['go']['pulse']['App']['ShowWindow']();
}

export function StartCore() {
  return window['go']['pulse']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['pulse']['App']['StopCore']();
}

export function TestProxyGroup(arg1) {
  return window['go']['pulse']['App']['TestProxyGroup'](arg1);
}

export function TestProxyNode(arg1, arg2) {
  return window['go']['pulse']['App']['TestProxyNode'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['pulse']['App']['UpdateProfile'](arg1);
}

export function UpdateProfileSource(arg1, arg2) {
  return window['go']['pulse']['App']['UpdateProfileSource'](arg1, arg2);
}

export function UpdateProfileWithProxy(arg1, arg2) {
  return window['go']['pulse']['App']['UpdateProfileWithProxy'](arg1, arg2);
}

export function UpdateProvider(arg1) {
  return window['go']['pulse']['App']['UpdateProvider'](arg1);
}
