// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProfileFromURL(arg1:string,arg2:string):Promise<main.Profile>;

export function CloseAllConnections():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function FetchConnections():Promise<Array<main.ConnectionRow>>;

export function FetchProviders():Promise<Array<main.ProviderRow>>;

export function FetchProxyGroups():Promise<Array<main.ProxyGroup>>;

export function FetchRules():Promise<Array<main.RuleRow>>;

export function GetLogs():Promise<Array<main.LogLine>>;

export function GetSnapshot():Promise<main.RuntimeState>;

export function ImportProfile(arg1:string,arg2:string):Promise<main.Profile>;

export function OpenDataDirectory():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadBackgroundImageDataURL(arg1:string):Promise<string>;

export function ReadProfileContent(arg1:string):Promise<string>;

export function RestartCore():Promise<void>;

export function SaveProfileContent(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectBackgroundImage():Promise<string>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;

export function UpdateProfile(arg1:string):Promise<main.Profile>;

export function UpdateProvider(arg1:string):Promise<void>;
