// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfileFromURL(arg1, arg2) {
  return window['go']['main']['App']['AddProfileFromURL'](arg1, arg2);
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function FetchConnections() {
  return window['go']['main']['App']['FetchConnections']();
}

export function FetchProviders() {
  return window['go']['main']['App']['FetchProviders']();
}

export function FetchProxyGroups() {
  return window['go']['main']['App']['FetchProxyGroups']();
}

export function FetchRules() {
  return window['go']['main']['App']['FetchRules']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ImportProfile(arg1, arg2) {
  return window['go']['main']['App']['ImportProfile'](arg1, arg2);
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReadBackgroundImageDataURL(arg1) {
  return window['go']['main']['App']['ReadBackgroundImageDataURL'](arg1);
}

export function ReadProfileContent(arg1) {
  return window['go']['main']['App']['ReadProfileContent'](arg1);
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']();
}

export function SaveProfileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileContent'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectBackgroundImage() {
  return window['go']['main']['App']['SelectBackgroundImage']();
}

export function SelectProxy(arg1, arg2) {
  return window['go']['main']['App']['SelectProxy'](arg1, arg2);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function StartCore() {
  return window['go']['main']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}
